export const PRIMARY = '#1f2123'
export const PRIMARY_TEXT = '#eceeee'
export const SECONDARY_TEXT = '#8fa0a3'
export const INPUT_BG = '#2b2c2f'
export const BLACK = '#030304'
export const GRAY = '#eceeee2b'
